MATCHES_PLAYED = {'1. FC Kaiserslautern': 12,
                  '1. FC Nürnberg': 8,
                  '1. FC Saarbrücken': 2,
                  'AC Chievo Verona': 2,
                  'AC Milan': 249,
                  'AC Sparta Praha': 32,
                  'ACF Fiorentina': 45,
                  'AE Larisa': 2,
                  'AEK Athens': 62,
                  'AEL Limassol': 10,
                  'AFC Ajax': 193,
                  'AIK Solna': 16,
                  'AJ Auxerre': 24,
                  'APOEL Nikosia': 68,
                  'AS Monaco': 84,
                  'AS Roma': 89,
                  'AS Saint-Etienne': 41,
                  'AS Trencin': 2,
                  'ASK Vorwarts Berlin': 22,
                  'AZ Alkmaar': 10,
                  'Aalborg BK': 24,
                  'Aarhus GF': 18,
                  'Abderden': 12,
                  'Admira Wien': 2,
                  'Akademisk BK': 4,
                  'Aktobe': 16,
                  'Alania Vladikavkaz': 2,
                  'Anorthosis Famagusta': 36,
                  'Apollon Limassol': 6,
                  'Araks Ararat': 4,
                  'Ards': 2,
                  'Arges Pitesti': 8,
                  'Aris Bonnevoie': 6,
                  'Arsenal FC': 193,
                  'Astana': 12,
                  'Astana-64': 6,
                  'Aston Villa FC': 15,
                  'Athletic Bilbao': 28,
                  'Athlone Town': 4,
                  'Atletico Madrid': 101,
                  'Atvidabergs FF': 8,
                  'Austria Wien': 73,
                  'Avenir Beggen': 12,
                  'B 1903 Kobenhavn': 8,
                  'B 1909 Odense': 6,
                  'B 1913 Odense': 4,
                  'B36 Torshavn': 12,
                  'B68 Toftir': 2,
                  'BATE Borisov': 82,
                  'BFC Dynamo': 38,
                  'BSC Young Boys': 25,
                  'BSG Chemie Leipzig': 2,
                  'Baku': 6,
                  'Banants': 2,
                  'Bangor City': 2,
                  'Banik Ostrava': 16,
                  'Barry Town': 14,
                  'Basel': 98,
                  'Bayer 04 Leverkusen': 97,
                  'Bayern München': 311,
                  'Beitar Jerusalem': 16,
                  'Belshina Bobruisk': 4,
                  'Beşiktaş İstanbul JK': 68,
                  'Birkirkara': 10,
                  'Blackburn Rovers FC': 6,
                  'Boavista FC': 24,
                  'Bohemians': 18,
                  'Bohemians EKD Praha': 4,
                  'Bologna FC': 3,
                  'Borac Banja Luka': 2,
                  'Borussia Dortmund': 114,
                  'Borussia Monchengladbach': 39,
                  'Brann': 6,
                  'Breidablik': 2,
                  'Brondby IF': 42,
                  'Budapest Honved SE': 22,
                  'Budapesti Vasas': 27,
                  'Budapesti Voros Lobogo': 4,
                  'Buducnost': 4,
                  'Burnley FC': 4,
                  'Bursaspor': 6,
                  'CA Osasuna': 2,
                  'CCA Bucuresti': 5,
                  'CDNA Sofia': 21,
                  'CFR Cluj': 22,
                  'CSKA Moskva': 82,
                  'CSKA Sofia': 77,
                  'Cagliari Calcio': 4,
                  'Celta Vigo': 10,
                  'Celtic FC': 176,
                  'Chelsea FC': 152,
                  'Cliftonville': 6,
                  'Club Brugge': 83,
                  'Coleraine': 2,
                  'Cork Celtic': 2,
                  'Cork City': 8,
                  'Cork Hibernians': 2,
                  'Crusaders': 10,
                  'Crvena Zvezda': 108,
                  'Csepel SC': 2,
                  'Cwmbran Town': 2,
                  'DOS Utrecht': 2,
                  'DSO Spartak Hradec Kralove': 4,
                  'DWS Amsterdam': 6,
                  'Dacia Chisinau': 2,
                  'Daugava Daugavpils': 2,
                  'Debreceni VSC': 32,
                  'Deportivo La Coruna': 62,
                  'Derby County FC': 12,
                  'Derry City': 10,
                  'Dila Gori': 2,
                  'Dinamo Bucuresti': 66,
                  'Dinamo Kiev': 220,
                  'Dinamo Minsk': 12,
                  'Dinamo Moskva': 2,
                  'Dinamo Tbilisi': 32,
                  'Dinamo Tirana': 14,
                  'Dinamo Zagreb': 104,
                  'Djurgardens IF': 16,
                  'Dnepr Dnepropetrovsk': 14,
                  'Dnepr Mogilev': 2,
                  'Drogheda United': 4,
                  'Drumcondra Dublin': 6,
                  'Dukla Praha': 45,
                  'Dunakanyar-Vac': 2,
                  'Dunaujvaros': 4,
                  'Dundalk': 20,
                  'Dundee FC': 8,
                  'Dundee United': 8,
                  'Dynamo Dresden': 30,
                  'EB / Streymur': 6,
                  'EPA Larnaca': 2,
                  'Eintracht Braunschweig': 5,
                  'Elfsborg': 10,
                  'Esbjerg fB': 12,
                  'Etar Tarnovo': 2,
                  'Everton FC': 10,
                  'F91 Dudelange': 30,
                  'FBK Kaunas': 24,
                  'FC Aarau': 4,
                  'FC Ararat': 6,
                  'FC Barcelona': 278,
                  'FC Carl Zeiss Jena': 6,
                  'FC Jazz': 4,
                  'FC Karl-Marx-Stadt': 2,
                  'FC Kuusysi': 14,
                  'FC La Chaux-de-Fonds': 4,
                  'FC Luzern': 2,
                  'FC Metz': 2,
                  'FC Nantes': 40,
                  'FC Norma Tallinn': 4,
                  'FC Politehnica Timisoara': 4,
                  'FC Porto': 215,
                  'FC RB Salzburg': 42,
                  'FC Reipas Lahti': 8,
                  'FC Santa Coloma': 12,
                  'FC Schalke 04': 69,
                  'FC Slavia Mozyr': 4,
                  'FC Tiraspol': 2,
                  'FC Tirol': 8,
                  'FC Twente': 14,
                  'FC Universitatea Craiova': 12,
                  'FC Yerevan': 2,
                  'FC Zurich': 45,
                  'FH': 18,
                  'FK Ekranas': 20,
                  'FK Inter Bratislava': 12,
                  'FK Kareda Kaunas': 4,
                  'FK Leotar': 4,
                  'FK Modrica': 4,
                  'FK Mogren': 6,
                  'FK Obilic': 4,
                  'FK Partizani Tirana': 16,
                  'FK Pobeda': 4,
                  'FK Rudar Pljevlja': 6,
                  'FK Sarajevo': 14,
                  'FK Sileks': 4,
                  'FK Vllaznia': 8,
                  'FK Zalgiris Vilnius': 10,
                  'FK Zeta': 4,
                  'Fenerbahçe İstanbul SK': 101,
                  'Ferencvaros': 36,
                  'Feyenoord Rotterdam': 83,
                  'Flora Tallinn': 14,
                  'Floriana': 16,
                  'Fola Esch': 4,
                  'Fram Reykjavik': 8,
                  'Frankfurter SG Eintracht': 7,
                  'Fredrikstad FK': 8,
                  'GI Gota': 2,
                  'Galatasaray İstanbul AŞ': 163,
                  'Girondins Bordeaux': 50,
                  'Glenavon FC': 2,
                  'Glentoran': 28,
                  'Gomel': 2,
                  'Gornik Zabrze': 43,
                  'Grasshoppers Zurich': 54,
                  'Grazer AK': 10,
                  'Grevenmacher': 2,
                  'Gwardia Warszawa': 5,
                  'Gyori ETO': 10,
                  'HB': 18,
                  'HB Koge': 2,
                  'HJK Helsinki': 64,
                  'HNK Gorica': 12,
                  'HNK Rijeka': 2,
                  'HPS Helsinki': 2,
                  'HSK Zrinjski Mostar': 6,
                  'Hajduk Split': 40,
                  'Haka Valkeakoski': 26,
                  'Halmstads BK': 10,
                  'Hamburger SV': 41,
                  'Hammarby': 2,
                  'Hamrun Spartans': 8,
                  'Hansa Rostock': 2,
                  'Hapoel Haifa': 4,
                  'Hapoel Ironi Kiryat Shmona': 6,
                  'Hapoel Tel Aviv': 14,
                  'Heart of Midlothian': 8,
                  'Hellas Verona': 4,
                  'Helsingborgs IF': 16,
                  'Helsingfors IFK': 4,
                  'Hertha BSC': 14,
                  'Hibernian FC': 6,
                  'Hibernians': 20,
                  'Hvidovre IF': 8,
                  'IA Akranes': 22,
                  'IB Keflavik': 8,
                  'IB Vestmannaeyja': 8,
                  'IFK Goteborg': 82,
                  'IFK Malmo': 6,
                  'IFK Norrkoping': 12,
                  'IK Start': 4,
                  'Ilves Tampere': 2,
                  'Inter Baku PIK': 6,
                  'Inter Turku': 2,
                  'Internazionale': 166,
                  'Ipswich Town FC': 4,
                  'Irtysh Pavlodar': 2,
                  'Jeunesse Esch': 49,
                  'Juventus': 238,
                  'K Lierse SK': 10,
                  'KA Akureyri': 2,
                  'KAA Gent': 10,
                  'KB Kobenhavn': 13,
                  'KF Tirana': 36,
                  'KI Klaksvik': 4,
                  'KPV Kokkola': 2,
                  'KR Reykjavik': 20,
                  'KRC Genk': 22,
                  'KS Elbasani': 4,
                  'KS Flamurtari Vlore': 2,
                  'KSK Beveren': 6,
                  'KV Mechelen': 6,
                  'Kairat': 2,
                  'Kalmar FF': 2,
                  'Kapaz': 4,
                  'Khazar Lankaran': 2,
                  'Kilmarnock FC': 4,
                  'Kispesti Honved': 6,
                  'Kobenhavn': 64,
                  'Koge BK': 2,
                  'Koln': 17,
                  'Koper': 2,
                  'Kosice': 14,
                  'Kuopion PS': 6,
                  'LKS Lodz': 6,
                  'La Fiorita': 2,
                  'Lantana Tallinn': 2,
                  'Lausanne Sports': 2,
                  'Lech Poznan': 24,
                  'Leeds United FC': 40,
                  'Legia Warsaw': 48,
                  'Levadia': 26,
                  'Levski Sofia': 56,
                  'Liepajas Metalurgs': 6,
                  'Lille OSC': 42,
                  'Lillestrom': 14,
                  'Limerick FC': 4,
                  'Lincoln Red Imps': 6,
                  'Linfield': 63,
                  'Linzer ASK': 2,
                  'Lisburn Distillery': 2,
                  'Liverpool FC': 181,
                  'Llanelli': 2,
                  'Lokomotiv Moskva': 38,
                  'Lokomotiv Sofia': 8,
                  'Lugano': 2,
                  'Lusitanos': 4,
                  'Lyn Oslo': 10,
                  'Lyngby BK': 6,
                  'MFK Ruzomberok': 4,
                  'MSK Zilina': 26,
                  'MTK': 20,
                  'MYPA': 4,
                  'Maccabi Haifa': 38,
                  'Maccabi Tel Aviv': 40,
                  'Magdeburg': 8,
                  'Makedonija': 2,
                  'Malaga CF': 12,
                  'Malmo FF': 69,
                  'Manchester City FC': 42,
                  'Manchester United FC': 261,
                  'Marsaxlokk': 2,
                  'Metalist Kharkiv': 2,
                  'Metalurgi Rustavi': 4,
                  'Midtjylland': 4,
                  'Milsami Orhei': 4,
                  'Mlada Boleslav': 4,
                  'Molde FK': 22,
                  'Montpellier HSC': 6,
                  'Moss FK': 2,
                  'Motherwell FC': 2,
                  'Murata': 4,
                  'NK Brotnjo': 2,
                  'NK Domzale': 8,
                  'NK Maribor': 60,
                  'NK Siroki Brijeg': 6,
                  'NK Zagreb': 2,
                  'NSI': 2,
                  'Neftchi PFC Baku': 18,
                  'Neuchatel Xamax FC': 8,
                  'Newcastle United FC': 24,
                  'Nomme Kalju': 4,
                  'Nordsjaelland': 8,
                  'Nottingham Forest FC': 20,
                  'OGC Nice': 14,
                  'OPS Oulu': 4,
                  'Odense BK': 10,
                  'Olimpija Ljubljana': 6,
                  'Olympiacos': 146,
                  'Olympique Lyon': 124,
                  'Olympique Marseille': 102,
                  'Omonia Nicosia': 54,
                  'Orgryte IS': 2,
                  'Osters IF': 8,
                  'Otelul Galati': 6,
                  'PAOK FC': 14,
                  'PFC Beroe': 2,
                  'PFC Litex Lovech': 16,
                  'PFC Lokomotiv Plovdiv': 2,
                  'PFC Ludogorets Razgrad': 22,
                  'PFC Slavia Sofia': 4,
                  'PSV Eindhoven': 161,
                  'Pacos de Ferreira': 2,
                  'Panathinaikos FC': 157,
                  'Paris Saint-Germain': 80,
                  'Parma': 12,
                  'Partizan Belgrade': 101,
                  'Petrolul Ploiesti': 8,
                  'Petrzalka Akademia': 18,
                  'Pezoporikos Larnaca': 2,
                  'Polonia Bytom': 6,
                  'Polonia Warszawa': 4,
                  'Portadown': 6,
                  'Progres Niedercorn': 4,
                  'Pyunik': 34,
                  'Qarabag FK': 8,
                  'RC Lens': 12,
                  'RC Strasbourg': 6,
                  'RCD Mallorca': 10,
                  'RSC Anderlecht': 193,
                  'RWD Molenbeek': 4,
                  'Raba ETO Gyor': 6,
                  'Rabat Ajax': 4,
                  'Rabotnicki': 14,
                  "Ranger's": 2,
                  'Rangers FC': 161,
                  'Rapid Bucuresti': 8,
                  'Rapid JC Heerlen': 2,
                  'Rapid Wien': 77,
                  'Real Betis': 8,
                  'Real Madrid CF': 397,
                  'Real Sociedad': 26,
                  'Red Boys Differdange': 2,
                  'Renova': 2,
                  'Rhyl': 4,
                  'Rosenborg BK': 132,
                  'Rot-Weiss Essen': 2,
                  'Royal Antwerp FC': 2,
                  'Rubin Kazan': 16,
                  'Ruch Chorzow': 14,
                  'S.S. Folgore Falciano Calcio': 2,
                  'SC Motor Jena': 2,
                  'SC Wismut Karl-Marx-Stadt': 16,
                  'SK Slovan Bratislava': 34,
                  'SK Sturm Graz': 40,
                  'SK VOEST Linz': 2,
                  'SL Benfica': 228,
                  'SS Lazio': 52,
                  'SSC Napoli': 22,
                  'SSW Innsbruck': 18,
                  'Servette Geneve': 21,
                  'Sevilla FC': 32,
                  'Shakhtar Donetsk': 108,
                  'Shakhter Karagandy': 8,
                  'Shakhtyor Soligorsk': 2,
                  'Shamkir': 6,
                  'Shamrock Rovers': 20,
                  'Shelbourne': 20,
                  'Sheriff Tiraspol': 56,
                  'Shirak': 6,
                  'Shkendija': 2,
                  'Silkeborg IF': 2,
                  'Sion': 8,
                  'Sioni Bolnisi': 4,
                  'Sivasspor': 2,
                  'Skeid Oslo': 2,
                  'Skenderbeu Korce': 16,
                  'Skonto': 42,
                  'Slask Wroclaw': 6,
                  'Slavia Praha': 28,
                  'Sliema Wanderers': 24,
                  'Sligo Rovers': 4,
                  'Sloga Jugomagnat Skopje': 10,
                  'Slovan Liberec': 8,
                  'Sparta Praha': 108,
                  'Sparta Rotterdam': 6,
                  'Spartak Moskva': 114,
                  'Spartak Plovdiv': 4,
                  'Spartak TAZ Trnava': 24,
                  'Spora Luxemburg': 7,
                  'Sporting Braga': 18,
                  'Sporting CP': 78,
                  "St Patrick's Athletic": 8,
                  'St. Gallen': 2,
                  'Stabaek': 4,
                  'Stade Dudelange': 4,
                  'Stade Reims': 24,
                  'Stal Mielec': 4,
                  'Standard Liege': 56,
                  'Steaua Bucuresti': 132,
                  'Stjarnan': 2,
                  'Stromsgodset IF': 4,
                  'Sutjeska Niksic': 4,
                  'Szombierki Bytom': 4,
                  'TJ Vitkovice': 4,
                  'TPS Turku': 10,
                  'TSV 1860 Munchen': 6,
                  'TVMK': 2,
                  'Tampere United': 12,
                  'Tavriya Simferopol': 4,
                  'Teplice': 2,
                  'The New Saints': 22,
                  'Thun': 10,
                  'Tobol': 2,
                  'Torino FC': 4,
                  'Torpedo Kutaisi': 10,
                  'Torpedo Moskva': 4,
                  'Tottenham Hotspur FC': 20,
                  'Toulouse FC': 2,
                  'Trabzonspor AŞ': 28,
                  'Trakia Plovdiv': 4,
                  'Tre Fiori': 6,
                  'Tre Penne': 4,
                  'UC Sampdoria': 13,
                  'UE Sant Julia': 4,
                  'UT Arad': 6,
                  'Udinese Calcio': 12,
                  'Ujpesti Dozsa SC': 44,
                  'Ulisses': 2,
                  'Union Luxembourg': 10,
                  'Unirea Urziceni': 8,
                  'Vagur': 2,
                  'Valencia CF': 114,
                  'Valerenga IF': 14,
                  'Valletta': 36,
                  'Valur Reykjavik': 18,
                  'Vardar Skopje': 18,
                  'Vaslui': 4,
                  'Vejle BK': 12,
                  'Ventspils': 20,
                  'VfB Stuttgart': 29,
                  'VfL Wolfsburg': 16,
                  'Videoton': 6,
                  'Viking FK': 14,
                  'Vikingur Reykjavik': 6,
                  'Viktoria Plzen': 26,
                  'Villarreal CF': 32,
                  'Vitoria Guimaraes': 2,
                  'Vitosha Sofia': 2,
                  'Vojvodina': 9,
                  'WIT Georgia': 6,
                  'Waterford AFC': 14,
                  'Werder Bremen': 66,
                  'Widzew Lodz': 26,
                  'Wiener Sport-Club': 12,
                  'Willem II Tilburg': 6,
                  'Wisla Krakow': 32,
                  'Wolverhampton Wanderers FC': 8,
                  'Zaglebie Lubin': 4,
                  'Zalaegerszegi TE': 4,
                  'Zalgiris Vilnius': 4,
                  'Zbrojovka Brno': 4,
                  'Zeljeznicar Sarajevo': 16,
                  'Zenit St. Petersburg': 58,
                  'Zestafoni': 6,
                  'Zimbru Chisinau': 16,
                  'Zorya Voroshilovgrad': 4,
                  'Zulte-Waregem': 2,
                  'sc Heerenveen': 6}
