TEAMS_CODE = {'TPS Turku': 0,
              'KB Kobenhavn': 1,
              'AC Milan': 2,
              'ACF Fiorentina': 3,
              'Bayern München': 4,
              'Austria Wien': 5,
              'Basel': 6,
              'Crvena Zvezda': 7,
              'CSKA Sofia': 8,
              'KR Reykjavik': 9,
              'Galatasaray İstanbul AŞ': 10,
              'Hibernians': 11,
              'SL Benfica': 12,
              'Standard Liege': 13,
              'Leeds United FC': 14,
              'UT Arad': 15,
              'ASK Vorwarts Berlin': 16,
              'Avenir Beggen': 17,
              'Omonia Nicosia': 18,
              'Feyenoord Rotterdam': 19,
              'Real Madrid CF': 20,
              'Osters IF': 21,
              'AS Saint-Etienne': 22,
              'Dinamo Kiev': 23,
              'Celtic FC': 24,
              'Linfield': 25,
              'Ferencvaros': 26,
              'Waterford AFC': 27,
              'Spartak TAZ Trnava': 28,
              'KF Tirana': 29,
              'Lyn Oslo': 30,
              'Legia Warsaw': 31,
              'Panathinaikos FC': 32,
              'Lusitanos': 33,
              'Shirak': 34,
              'EB / Streymur': 35,
              'Tre Penne': 36,
              'Birkirkara': 37,
              'BATE Borisov': 38,
              'Dinamo Tbilisi': 39,
              'Fola Esch': 40,
              'FK Ekranas': 41,
              'Sheriff Tiraspol': 42,
              'Viktoria Plzen': 43,
              'Steaua Bucuresti': 44,
              'Cliftonville': 45,
              'Elfsborg': 46,
              'Gyori ETO': 47,
              'HJK Helsinki': 48,
              'Sligo Rovers': 49,
              'Neftchi PFC Baku': 50,
              'SK Slovan Bratislava': 51,
              'The New Saints': 52,
              'Shakhter Karagandy': 53,
              'Daugava Daugavpils': 54,
              'Dinamo Zagreb': 55,
              'FH': 56,
              'Maccabi Tel Aviv': 57,
              'Nomme Kalju': 58,
              'Zeljeznicar Sarajevo': 59,
              'Skenderbeu Korce': 60,
              'Sutjeska Niksic': 61,
              'Vardar Skopje': 62,
              'Molde FK': 63,
              'NK Maribor': 64,
              'PFC Ludogorets Razgrad': 65,
              'Partizan Belgrade': 66,
              'Olympique Lyon': 67,
              'PAOK FC': 68,
              'Nordsjaelland': 69,
              'PSV Eindhoven': 70,
              'APOEL Nikosia': 71,
              'FC RB Salzburg': 72,
              'Fenerbahçe İstanbul SK': 73,
              'Grasshoppers Zurich': 74,
              'Metalist Kharkiv': 75,
              'Zulte-Waregem': 76,
              'Zenit St. Petersburg': 77,
              'Pacos de Ferreira': 78,
              'FC Schalke 04': 79,
              'Arsenal FC': 80,
              'Real Sociedad': 81,
              'Manchester United FC': 82,
              'Kobenhavn': 83,
              'Olympiacos': 84,
              'Chelsea FC': 85,
              'SSC Napoli': 86,
              'Olympique Marseille': 87,
              'Atletico Madrid': 88,
              'FC Barcelona': 89,
              'Borussia Dortmund': 90,
              'FC Porto': 91,
              'AFC Ajax': 92,
              'Bayer 04 Leverkusen': 93,
              'Shakhtar Donetsk': 94,
              'Juventus': 95,
              'Paris Saint-Germain': 96,
              'RSC Anderlecht': 97,
              'CSKA Moskva': 98,
              'Manchester City FC': 99,
              'Dukla Praha': 100,
              'Lillestrom': 101,
              'Trabzonspor AŞ': 102,
              'Budapesti Vasas': 103,
              'Levski Sofia': 104,
              'Dynamo Dresden': 105,
              'Floriana': 106,
              'Kuopion PS': 107,
              'Dinamo Bucuresti': 108,
              'Valur Reykjavik': 109,
              'Torpedo Moskva': 110,
              'FC Nantes': 111,
              'B 1903 Kobenhavn': 112,
              'SSW Innsbruck': 113,
              'Borussia Monchengladbach': 114,
              'Jeunesse Esch': 115,
              'Club Brugge': 116,
              'Halmstads BK': 117,
              'Slask Wroclaw': 118,
              'Glentoran': 119,
              'Liverpool FC': 120,
              'FC Santa Coloma': 121,
              'Tre Fiori': 122,
              'F91 Dudelange': 123,
              'Valletta': 124,
              'FK Mogren': 125,
              'Shamrock Rovers': 126,
              'Pyunik': 127,
              'Bangor City': 128,
              'Maccabi Haifa': 129,
              'Rosenborg BK': 130,
              'Zestafoni': 131,
              'Malmo FF': 132,
              'Skonto': 133,
              'SK Sturm Graz': 134,
              'Shkendija': 135,
              'Flora Tallinn': 136,
              'HB': 137,
              'Tobol': 138,
              'Wisla Krakow': 139,
              'PFC Litex Lovech': 140,
              'Borac Banja Luka': 141,
              'Breidablik': 142,
              'Dacia Chisinau': 143,
              'Videoton': 144,
              'Rangers FC': 145,
              'KRC Genk': 146,
              'FC Twente': 147,
              'Odense BK': 148,
              'Rubin Kazan': 149,
              'FC Zurich': 150,
              'Vaslui': 151,
              'Villarreal CF': 152,
              'Udinese Calcio': 153,
              'Internazionale': 154,
              'Lille OSC': 155,
              'Otelul Galati': 156,
              'Valencia CF': 157,
              'AS Monaco': 158,
              'AEK Athens': 159,
              'FK Vllaznia': 160,
              'Haka Valkeakoski': 161,
              'Koln': 162,
              'Nottingham Forest FC': 163,
              'Zbrojovka Brno': 164,
              'Bohemians': 165,
              'IA Akranes': 166,
              'Lokomotiv Sofia': 167,
              'Progres Niedercorn': 168,
              'Ujpesti Dozsa SC': 169,
              'Abderden': 170,
              'Valerenga IF': 171,
              'Girondins Bordeaux': 172,
              'Ilves Tampere': 173,
              'KS Elbasani': 174,
              'Lech Poznan': 175,
              'BFC Dynamo': 176,
              'VfB Stuttgart': 177,
              'AC Sparta Praha': 178,
              'Athletic Bilbao': 179,
              'IFK Goteborg': 180,
              'Budapest Honved SE': 181,
              'Dnepr Dnepropetrovsk': 182,
              'KSK Beveren': 183,
              'Lyngby BK': 184,
              'Widzew Lodz': 185,
              'Rapid Wien': 186,
              'Brondby IF': 187,
              'Slavia Praha': 188,
              'Alania Vladikavkaz': 189,
              'AJ Auxerre': 190,
              '1. FC Kaiserslautern': 191,
              'Sparta Praha': 192,
              'FC Universitatea Craiova': 193,
              'Fram Reykjavik': 194,
              'Beşiktaş İstanbul JK': 195,
              'Kispesti Honved': 196,
              'Hamrun Spartans': 197,
              'Union Luxembourg': 198,
              'UC Sampdoria': 199,
              'KS Flamurtari Vlore': 200,
              'Hansa Rostock': 201,
              'Zaglebie Lubin': 202,
              'Portadown': 203,
              'Dundalk': 204,
              'Etar Tarnovo': 205,
              'Apollon Limassol': 206,
              'OGC Nice': 207,
              'CDNA Sofia': 208,
              'Wiener Sport-Club': 209,
              'FK Inter Bratislava': 210,
              'Petrolul Ploiesti': 211,
              'Csepel SC': 212,
              'LKS Lodz': 213,
              'Wolverhampton Wanderers FC': 214,
              'B 1909 Odense': 215,
              'Sparta Rotterdam': 216,
              'BSC Young Boys': 217,
              'Frankfurter SG Eintracht': 218,
              'Skeid Oslo': 219,
              'Gornik Zabrze': 220,
              'FC Karl-Marx-Stadt': 221,
              'Trakia Plovdiv': 222,
              'Djurgardens IF': 223,
              'FK Sarajevo': 224,
              'Rapid Bucuresti': 225,
              'Hvidovre IF': 226,
              'Eintracht Braunschweig': 227,
              'Dinamo Tirana': 228,
              'IB Vestmannaeyja': 229,
              'Sporting CP': 230,
              'Viking FK': 231,
              'Limerick FC': 232,
              'OPS Oulu': 233,
              'Banik Ostrava': 234,
              'Esbjerg fB': 235,
              'Spartak Moskva': 236,
              'Szombierki Bytom': 237,
              'IB Keflavik': 238,
              'Derry City': 239,
              'Drumcondra Dublin': 240,
              'Linzer ASK': 241,
              'Lausanne Sports': 242,
              'Kilmarnock FC': 243,
              'Stade Dudelange': 244,
              'Sliema Wanderers': 245,
              'Werder Bremen': 246,
              'Inter Baku PIK': 247,
              'Anorthosis Famagusta': 248,
              'Tampere United': 249,
              'Murata': 250,
              'Llanelli': 251,
              'Aktobe': 252,
              'Drogheda United': 253,
              'Rabotnicki': 254,
              'NSI': 255,
              'FBK Kaunas': 256,
              'Ventspils': 257,
              'Buducnost': 258,
              'FK Modrica': 259,
              'Levadia': 260,
              'NK Domzale': 261,
              'Petrzalka Akademia': 262,
              'Brann': 263,
              'Aalborg BK': 264,
              'Beitar Jerusalem': 265,
              'MTK': 266,
              'Vitoria Guimaraes': 267,
              'AS Roma': 268,
              'CFR Cluj': 269,
              'Orgryte IS': 270,
              'PFC Beroe': 271,
              'TJ Vitkovice': 272,
              'Rabat Ajax': 273,
              'Arges Pitesti': 274,
              'Vejle BK': 275,
              'Hajduk Split': 276,
              'IK Start': 277,
              'Servette Geneve': 278,
              'Red Boys Differdange': 279,
              'FK Partizani Tirana': 280,
              'Ruch Chorzow': 281,
              'Hamburger SV': 282,
              'RC Strasbourg': 283,
              'Olimpija Ljubljana': 284,
              'KI Klaksvik': 285,
              'Shelbourne': 286,
              'FC Norma Tallinn': 287,
              'Tavriya Simferopol': 288,
              'Vikingur Reykjavik': 289,
              'FC Kuusysi': 290,
              'Sion': 291,
              'FK Zalgiris Vilnius': 292,
              'Aarhus GF': 293,
              'Neuchatel Xamax FC': 294,
              'Aston Villa FC': 295,
              'Raba ETO Gyor': 296,
              'Sioni Bolnisi': 297,
              'TVMK': 298,
              'Liepajas Metalurgs': 299,
              'Cork City': 300,
              'MYPA': 301,
              'Shakhtyor Soligorsk': 302,
              'Baku': 303,
              'NK Siroki Brijeg': 304,
              'HNK Gorica': 305,
              'B36 Torshavn': 306,
              'Mlada Boleslav': 307,
              'Debreceni VSC': 308,
              'Heart of Midlothian': 309,
              'MFK Ruzomberok': 310,
              'Slovan Liberec': 311,
              'CA Osasuna': 312,
              'AC Chievo Verona': 313,
              'Cwmbran Town': 314,
              'B68 Toftir': 315,
              'Zimbru Chisinau': 316,
              'FC Aarau': 317,
              'AIK Solna': 318,
              'Dinamo Minsk': 319,
              'Athlone Town': 320,
              'AZ Alkmaar': 321,
              'RWD Molenbeek': 322,
              'Magdeburg': 323,
              'Derby County FC': 324,
              'BSG Chemie Leipzig': 325,
              'FC Reipas Lahti': 326,
              'Aris Bonnevoie': 327,
              'FC La Chaux-de-Fonds': 328,
              'DWS Amsterdam': 329,
              'Bologna FC': 330,
              'Grevenmacher': 331,
              'Barry Town': 332,
              'FK Leotar': 333,
              'Irtysh Pavlodar': 334,
              'MSK Zilina': 335,
              'Grazer AK': 336,
              'Celta Vigo': 337,
              'SS Lazio': 338,
              'Newcastle United FC': 339,
              'Deportivo La Coruna': 340,
              'Lokomotiv Moskva': 341,
              'UE Sant Julia': 342,
              'Makedonija': 343,
              'Rhyl': 344,
              'WIT Georgia': 345,
              'HSK Zrinjski Mostar': 346,
              'Inter Turku': 347,
              'Stabaek': 348,
              'Kalmar FF': 349,
              'Sivasspor': 350,
              'FC Politehnica Timisoara': 351,
              'Dinamo Moskva': 352,
              'VfL Wolfsburg': 353,
              'Sevilla FC': 354,
              'Unirea Urziceni': 355,
              'FK Rudar Pljevlja': 356,
              'Hapoel Tel Aviv': 357,
              'Koper': 358,
              'Renova': 359,
              'Metalurgi Rustavi': 360,
              'Sporting Braga': 361,
              'KAA Gent': 362,
              'Tottenham Hotspur FC': 363,
              'Bursaspor': 364,
              'Torpedo Kutaisi': 365,
              'Astana-64': 366,
              'Belshina Bobruisk': 367,
              'Zalaegerszegi TE': 368,
              'Boavista FC': 369,
              'Hammarby': 370,
              'NK Zagreb': 371,
              'RC Lens': 372,
              'Blackburn Rovers FC': 373,
              'Hellas Verona': 374,
              'KA Akureyri': 375,
              'FC Tirol': 376,
              "St Patrick's Athletic": 377,
              'Sloga Jugomagnat Skopje': 378,
              'Zalgiris Vilnius': 379,
              'Kapaz': 380,
              'Araks Ararat': 381,
              'Dnepr Mogilev': 382,
              'Hapoel Haifa': 383,
              'HNK Rijeka': 384,
              'Hertha BSC': 385,
              'Teplice': 386,
              'RCD Mallorca': 387,
              'Parma': 388,
              'Willem II Tilburg': 389,
              'La Fiorita': 390,
              'Lincoln Red Imps': 391,
              'Banants': 392,
              'Stromsgodset IF': 393,
              'Qarabag FK': 394,
              'AEL Limassol': 395,
              'Khazar Lankaran': 396,
              'FK Zeta': 397,
              'FK Pobeda': 398,
              'Marsaxlokk': 399,
              "Ranger's": 400,
              'Toulouse FC': 401,
              'FK Sileks': 402,
              'Crusaders': 403,
              'Lantana Tallinn': 404,
              'FC Tiraspol': 405,
              'GI Gota': 406,
              'Kosice': 407,
              'FK Kareda Kaunas': 408,
              'FC Jazz': 409,
              'FC Slavia Mozyr': 410,
              'K Lierse SK': 411,
              'SK VOEST Linz': 412,
              'Coleraine': 413,
              'FC Ararat': 414,
              'Atvidabergs FF': 415,
              'Cork Celtic': 416,
              'Budapesti Voros Lobogo': 417,
              'Rot-Weiss Essen': 418,
              'Hibernian FC': 419,
              'Gwardia Warszawa': 420,
              'Stade Reims': 421,
              '1. FC Saarbrücken': 422,
              'Spora Luxemburg': 423,
              'Rapid JC Heerlen': 424,
              'IFK Norrkoping': 425,
              'Gomel': 426,
              'PFC Lokomotiv Plovdiv': 427,
              '1. FC Nürnberg': 428,
              'Akademisk BK': 429,
              'Ards': 430,
              'Polonia Bytom': 431,
              'SC Wismut Karl-Marx-Stadt': 432,
              'DOS Utrecht': 433,
              'HPS Helsinki': 434,
              'Fredrikstad FK': 435,
              'Dundee FC': 436,
              'Ipswich Town FC': 437,
              'Helsingfors IFK': 438,
              'Zorya Voroshilovgrad': 439,
              'Stal Mielec': 440,
              'Vitosha Sofia': 441,
              'AE Larisa': 442,
              'Pezoporikos Larnaca': 443,
              'Moss FK': 444,
              'IFK Malmo': 445,
              'DSO Spartak Hradec Kralove': 446,
              'Burnley FC': 447,
              'Glenavon FC': 448,
              'Royal Antwerp FC': 449,
              'CCA Bucuresti': 450,
              'S.S. Folgore Falciano Calcio': 451,
              'AS Trencin': 452,
              'Midtjylland': 453,
              'Dila Gori': 454,
              'Milsami Orhei': 455,
              'Astana': 456,
              'Stjarnan': 457,
              'Kairat': 458,
              'Thun': 459,
              'Real Betis': 460,
              'Everton FC': 461,
              'Vojvodina': 462,
              'FC Luzern': 463,
              'KV Mechelen': 464,
              'NK Brotnjo': 465,
              'Shamkir': 466,
              'Helsingborgs IF': 467,
              'Polonia Warszawa': 468,
              'Dunaujvaros': 469,
              'St. Gallen': 470,
              'HB Koge': 471,
              'TSV 1860 Munchen': 472,
              'sc Heerenveen': 473,
              'Koge BK': 474,
              'Torino FC': 475,
              'Cagliari Calcio': 476,
              'EPA Larnaca': 477,
              'KPV Kokkola': 478,
              'FC Carl Zeiss Jena': 479,
              'Admira Wien': 480,
              'Ulisses': 481,
              'Hapoel Ironi Kiryat Shmona': 482,
              'Motherwell FC': 483,
              'Malaga CF': 484,
              'Montpellier HSC': 485,
              'Cork Hibernians': 486,
              'Bohemians EKD Praha': 487,
              'Dundee United': 488,
              'B 1913 Odense': 489,
              'SC Motor Jena': 490,
              'Lisburn Distillery': 491,
              'Spartak Plovdiv': 492,
              'Vagur': 493,
              'PFC Slavia Sofia': 494,
              'Lugano': 495,
              'FK Obilic': 496,
              'FC Yerevan': 497,
              'FC Metz': 498,
              'Silkeborg IF': 499,
              'Dunakanyar-Vac': 500}
