TEAMS_MAPS = {'Villarreal': 'Villarreal CF',
              'Young Boys': 'BSC Young Boys',
              'Sevilla': 'Sevilla FC',
              'Barcelona': 'FC Barcelona',
              'LOSC': 'Lille OSC',
              'Chelsea': 'Chelsea FC',
              'Sheriff': 'Sheriff Tiraspol',
              'Club Brugge': 'Club Brugge',
              'Liverpool': 'Liverpool FC',
              'Sporting CP': 'Sporting CP',
              'Internazionale': 'Internazionale',
              'Ajax': 'AFC Ajax',
              'Shakhtar Donetsk': 'Shakhtar Donetsk',
              'Paris': 'AE Larisa',
              'Leipzig': 'BSG Chemie Leipzig',
              'Porto': 'FC Porto',
              'Milan': 'AC Milan',
              'Dortmund': 'Borussia Dortmund',
              'Real Madrid': 'Real Madrid CF',
              'Zenit': 'Zenit St. Petersburg',
              'Bayern': 'Bayern München',
              'Benfica': 'SL Benfica',
              'Wolfsburg': 'VfL Wolfsburg',
              'Salzburg': 'FC RB Salzburg',
              'Juventus': 'Juventus',
              'Dynamo Kyiv': 'Dinamo Kiev',
              'Malmö': 'Malmo FF',
              'Besiktas': 'Beşiktaş İstanbul JK',
              'Man. City': 'Manchester City FC',
              'Atlético': 'Atletico Madrid',
              'Man. United': 'Manchester United FC'
              }
